name: Docker build

on:
  pull_request:
    branches: "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build default
      run: docker build -t coiled/default default

    - name: Build test-conda-env-name
      run: docker build -t coiled/test-conda-env-name test-conda-env-name
    